### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getOrigin' of undefined

### ISSUE THREAD

**Issue by zx798928321** [roboshoes/hair#1]
em...hello,I I like the special effects you wrote，it is very interesting. But there are a few small problems，When I move from the bottom right to the left, then from left to right，After many times，It will make a mistake，On the index.js:3316 ，It is“Uncaught TypeError: Cannot read property 'getOrigin' of undefined”.One more question，On the index.js:3394,'var t = document.getElementById("tag"),' should be 'var t = document.getElementsByClassName("tag"),',I have solved the problem.But the first question, I can't find the reason.May I trouble you for a minute?
                                                                                                                                      Be deeply grateful.
![tim 20171007104011](https://user-images.githubusercontent.com/32585742/31304067-f5c2d42e-ab4b-11e7-8a9d-c719cbe72988.png)

**Comment by roboshoes** [comment]
Hi there,

wow. This is a pretty old project I haven't opened in a long time. So let's tackle both of those.
The easier question is about the `getElementById`. This on is correct because I have this element with the ID `"tag"` as you can see right [here](https://github.com/MathiasPaumgarten/hair/blob/master/source/index.html#L18). However this is just for the little black pop up with information about the experiment. 

As for the `getOrigin of undefined`. I vaguely remember having this problem. I guess I never really got around to investigating it. I would assume it has to do with the way I re-order the hair to be drawn. That would be right [here](https://github.com/MathiasPaumgarten/hair/blob/master/source/scripts/hair/utils/faceOrder.js). So I must assumein some weird edge cases it produces a sparse array. This could really quickly be fixed with a quick and dirty `if ( ! hair ) continue;`

I hope that helps.

**Comment by zx798928321** [comment]
oh，sorry.I was so busy recently that I almost forgot about it.
em...I used a very lazy way back，I added a judgment：
```js
if ( typeof(g) == 'undefined' ) {
    console.log('error');
} else {
    y = n.between(t, g.getOrigin()).normalize().multiply(20);
    a.suction && y.flip();
    g.setForce(y);
    g.draw(c);
}
```
Ha-ha，Thank you for your help，I gave this to a girl as a desktop wallpaper，I hope you don't mind.And my My English is not very good，It's bothering you.
Wish you a happy job and life.

**Comment by roboshoes** [comment]
I'm glad you find a quick for what you need 👍 

Also, I'm always glad if something I wrote and open source can be used by people. So I'm very excited about you turning it into a wallpaper!

Have a good one!
